events {}

http {
  client_max_body_size 2g;
  proxy_read_timeout 300s;

  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }

  server {
    listen 80;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    location /api/ { proxy_pass http://catalog-api:8080/; }
    location /geoserver/ { proxy_pass http://geoserver:8080/geoserver/; }
    location /ogc/ { proxy_pass http://pygeoapi:80/; }
    location /tiles/ { proxy_pass http://mapproxy:8080/; }
    location /identity/ { proxy_pass http://keycloak:8080/; }
    location /objects/ { proxy_pass http://minio:9000/; }
    location /storage-admin/ { proxy_pass http://minio:9001/; }
    location /database-admin/ { proxy_pass http://pgadmin:80/; }
    location /monitoring/ { proxy_pass http://grafana:3000/; }
    location /metrics/ { proxy_pass http://prometheus:9090/; }

    location = /health {
      default_type application/json;
      return 200 '{"ok":true,"gateway":"uganda-bms-enterprise-gis"}';
    }
  }
}
