services:
  demo:
  wms:
    md:
      title: Uganda BMS Cached Map Services
  tms:
  wmts:
caches:
  bms_structures_cache:
    grids: [webmercator]
    sources: [bms_structures]
    cache:
      type: file
      directory: /cache/structures
sources:
  bms_structures:
    type: wms
    req:
      url: http://geoserver:8080/geoserver/wms
      layers: bms:structures
grids:
  webmercator:
    base: GLOBAL_WEBMERCATOR
globals:
  cache:
    base_dir: /cache
  image:
    resampling_method: bicubic
